### ISSUE TITLE
[hdg-bot]: Add CONTRIBUTORS.md

### ISSUE THREAD

**Issue by yosileyid** [yosileyid/hdg-bot#3]
Need a contributors file to add user info for contributors.

**Comment by the-amazing-atharva** [comment]
Hi @yosileyid 

I am currently working on the CONTRIBUTING.md file that is below CODE OF CONDUCT

Is this the same file?

**Comment by the-amazing-atharva** [comment]
Also yesterday you had mentioned a link, could you send it again for contribuing?

**Comment by yosileyid** [comment]
> Also yesterday you had mentioned a link, could you send it again for contribuing?

Link to all our docs are [here](https://github.com/hasidicdevs/Docs).

**Comment by yosileyid** [comment]
> Hi @yosileyid
> 
> I am currently working on the CONTRIBUTING.md file that is below CODE OF CONDUCT
> 
> Is this the same file?

No, I also need a CONTRIBUTORS.md that will hold a list of all the people contributing to the repo. This is a npm package and I want contributors names to show up on the package page on npmjs.org. Feel free to join our discord server and I can help you out more.

**Comment by the-amazing-atharva** [comment]
I actually have used a similar thing for adding contributors but its just github profiles
Thoughts?
<a href="https://github.com/angular/angular-ja/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=angular/angular-ja" />
</a>

**Comment by yosileyid** [comment]
I like that, add something to the `Docs/CONTRIBUTING.md` for me to preview. Add yourself on there too :)

**Comment by the-amazing-atharva** [comment]
> I like that, add something to the `Docs/CONTRIBUTING.md` for me to preview. Add yourself on there too :)

Sure!
It will auto-add the contributors in sometime.
